### ISSUE TITLE
A way to stop the voice while it's reading?

### ISSUE THREAD

**Issue by JDBar** [Psychopoulet/simpletts#12]
Wasn't sure if this was possible or not with the way the script works, but I'd be great if there was a way to instantly stop any currently speaking voices.

Now that I'm looking, I found killing the "Microsoft Console Script Host" process with Task Manager in the middle of a read stopped the voice, so I'm guessing calling \<Child Process\>.kill() would be a quick and dirty way to do this.

**Comment by Psychopoulet** [comment]
aw sorry, I didn't see that. I'll try to do that.

**Comment by Psychopoulet** [comment]
done.
