### ISSUE TITLE
Question: more voices and languages

### ISSUE THREAD

**Issue by kordostomas** [Psychopoulet/simpletts#22]
Hello, I love the project. 
But it only has two voices
```
[
  { gender: 'male', name: 'microsoft david desktop' },
  { gender: 'female', name: 'microsoft zira desktop' }
]
```
Does it support adding more voices? Can I download them from somewhere?

**Comment by Psychopoulet** [comment]
if you use Microsoft Speech API, you can add voices following these instructions :
https://superuser.com/questions/590779/how-to-install-more-voices-to-windows-speech

**Comment by kordostomas** [comment]
Thank you, that worked, but unfortunately, [It](https://www.microsoft.com/en-us/download/details.aspx?id=27224) doesn't contain Slovak TTS package. Is there any way to download packages from somewhere else or in a different way?

**Comment by Psychopoulet** [comment]
I find some of them in french for me, but this package just expose the microsoft API, it does not references all ressources for it...
You should search into the microsoft ressources for your country, I really don't know where they are (neither if they exist ><)
